apiVersion: batch/v1
kind: Job
metadata:
  namespace: wandb-launch
spec:
  template:
    spec:
      containers:
        - name: wandb-launch-job
          image: ghcr.io/simonj0/arc-prize-2026-arc-agi-3:latest
          resources:
            requests:
              cpu: "8"
              memory: "80Gi"
            limits:
              cpu: "8"
              memory: "80Gi"
      restartPolicy: Never
